defaults:
  - layer: s4

_name_: model
prenorm: true
transposed: false
n_layers: 4
d_model: 256
residual: R
pool:
  _name_: pool
  stride: 1
  expand: null
norm: layer
dropout: 0.0
tie_dropout: false
track_norms: true # Logs to wandb

# Optional encoder/decoder, e.g. add positional embeddings or padding masks
encoder: null
decoder: null
