batch_size: 50
num_workers: 4
pin_memory: True
drop_last: True # We set this to true because of the recurrent state mechanism

train_resolution: 1
eval_resolutions:
  - 1
img_size: null
channels_last: true
