model_checkpoint:
  # _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${train.monitor} # name of the logged metric which determines when model is improving
  mode: ${train.mode} # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  dirpath: "checkpoints/"
  # this saves an annoying "epoch=12" which makes it annoying to pass on the command line; epochs are being logged through the verbose flag and logger anyways
  # seems like you can override the '.format_checkpoint_name' method of ModelCheckpoint to change this, but not worth
  # filename: "{epoch:02d}",
  filename: ${train.monitor}
  auto_insert_metric_name: False
  verbose: True

# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "val/acc" # name of the logged metric which determines when model is improving
#   mode: "max" # can be "max" or "min"
#   patience: 100 # how many epochs of not improving until training stops
#   min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement
