rich_model_summary:
  # _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 1

rich_progress_bar:
  # _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 1
  leave: true # Set to True to leave progress bar up after every epoch
