_name_: s4
d_state: 64
channels: 1
bidirectional: false
gate: null # 4 for GSS
gate_act: id # 4 for GSS
bottleneck: null # 4 for GSS
activation: gelu
mult_act: null
final_act: glu # Final activation after FF layer; new name for 'postact'
postact: null  # Deprecated for 'final_act'
initializer: null
weight_norm: false
# dropout: ${model.dropout} # Same as null
tie_dropout: ${oc.select:model.tie_dropout,null}
# Layer arguments
layer: fftconv
# Kernel arguments
mode: nplr
init: legs  # Initialization option; new name for 'measure'
measure: null  # Deprecated for 'init'
rank: 1
dt_min: 0.001
dt_max: 0.1
dt_transform: softplus  # Use 'exp' for any backwards-compatible experiments
lr:
  dt: 0.001
  A: 0.001
  B: 0.001
wd: 0.0 # Can be dictionary like lr
n_ssm: 1
drop_kernel: 0.0
deterministic: false # Special C init
l_max: ${oc.select:dataset.__l_max,null} # Grab dataset length if exists, otherwise set to 1 and kernel will automatically resize
verbose: true
