- _name_: s4
  l_max: ${dataset.__l_max}
  final_act: glu
  dropout: ${...dropout} # Same as null
  lr: ${optimizer.lr}
  n_ssm: 1
- _name_: s4
  l_max: ${dataset.__l_max}
  final_act: glu
  dropout: ${...dropout} # Same as null
  lr: ${optimizer.lr}
  n_ssm: 1
- _name_: ffn
  expand: 4
  activation: gelu
  dropout: ${...dropout} # Same as null
