# [22-02] TODO needs update
- _name_: s4
  l_max: ${dataset.__l_max}
  postact: glu
  dropout: ${...dropout} # Same as null
  lr: 0.0005
- _name_: s4
  l_max: ${dataset.__l_max}
  postact: glu
  dropout: ${...dropout} # Same as null
  lr: 0.0005
- _name_: ff
  expand: 4
  activation: gelu
  dropout: ${...dropout} # Same as null
  # transposed: False # Set by backbone
